name: flutter_spyglass
description: "Reliable service locator for Flutter."
version: 0.0.3
repository: https://github.com/leancodepl/spyglass/tree/main/packages/flutter_spyglass
homepage: https://github.com/leancodepl/spyglass

resolution: workspace

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  spyglass: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: ^19.0.1
