name: spyglass
description: "Reliable service locator for Dart."
version: 0.0.2
repository: https://github.com/leancodepl/spyglass/tree/main/packages/spyglass
homepage: https://github.com/leancodepl/spyglass

resolution: workspace

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  meta: ^1.11.0
  rxdart: ^0.28.0

dev_dependencies:
  fake_async: ^1.3.1
  leancode_lint: ^19.0.1
  test: ^1.24.0
